// THIS FILE IS AUTO GENERATED

/* eslint-disable */

export enum IconNames {
  'add' = 'add',
  'arrowForward' = 'arrowForward',
  'back' = 'back',
  'biz' = 'biz',
  'check' = 'check',
  'clipboard' = 'clipboard',
  'close' = 'close',
  'dashboard' = 'dashboard',
  'delete' = 'delete',
  'down' = 'down',
  'edit' = 'edit',
  'email' = 'email',
  'exit' = 'exit',
  'flag' = 'flag',
  'hand_shake' = 'hand_shake',
  'help' = 'help',
  'info' = 'info',
  'instagram' = 'instagram',
  'invoice' = 'invoice',
  'menu' = 'menu',
  'note' = 'note',
  'phone' = 'phone',
  'post' = 'post',
  'profile' = 'profile',
  'right' = 'right',
  'search' = 'search',
  'service' = 'service',
  'share' = 'share',
  'shop' = 'shop',
  'signOut' = 'signOut',
  'star' = 'star',
  'task' = 'task',
  'twitter' = 'twitter',
  'wallet' = 'wallet',
  'whatsapp_outline' = 'whatsapp_outline'
}
